#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define MAX_STRING 50
#define MAX_ALUNOS 20

#define NUM_MIN_ALUNO 1
#define NUM_MAX_ALUNO 9999

#define NOTA_MIN 0
#define NOTA_MAX 20

//#define PESO_MINITESTES 0.3
//#define PESO_TRABALHO 0.4
//#define PESO_TESTEPRATICO 0.3

#define MAX_RESERVAS 50

#define MEMORIA_DIN 1

#define MAX_PREGUNTASA 10
#define MAX_PREGUNTASB 10
#define MAX_PREGUNTASC 10
#define MAX_PREGUNTASD 4

#define MAX_REGPREGUNTAS 6

#endif // CONSTANTES_H_INCLUDED
